# Canonical development, validation, documentation, and release entry points.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

DIST_DIR := dist
DIST_SCRIPT := $(DIST_DIR)/adrctl.bash
DIST_CHECKSUM := $(DIST_SCRIPT).sha256

LIB_FILES := \
	lib/runtime.bash \
	lib/config.bash \
	lib/project.bash \
	lib/render.bash \
	lib/adr.bash \
	lib/commands.bash
ENTRYPOINT := src/adrctl.bash
SOURCE_FILES := $(LIB_FILES) $(ENTRYPOINT)

VENDOR_DIR := vendor
MKTEXT_VERSION := 0.0.7
MKTEXT_ARTIFACT := $(VENDOR_DIR)/mktext-v$(MKTEXT_VERSION).bash
MKTEXT_URL := https://github.com/wesley-dean/mktext/releases/download/v$(MKTEXT_VERSION)/mktext.bash
MKTEXT_SHA256 := 213cee4663512954f486c8a6ff00ddd36a9b4c48ceb3e9b71d9ec70a36c1e0dd

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/*.bats
TEST_RESULTS_DIR := test-results

DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
DOXYGEN_BASH_FILTER_URL := https://raw.githubusercontent.com/wesley-dean/bash-doxygen/refs/heads/main/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check checksums clean distclean docs docs-clean docs-stage format test test-report verify-mktext

all: build

## Build the exact single-file consumer artifact.
##
## This target is intentionally phony because VERSION, BUILD_DATE, and
## BUILD_COMMIT are build inputs rather than filesystem prerequisites.  Rebuilding
## prevents development metadata from leaking into a later release artifact.
## Full-line comments are stripped from maintained adrctl source during assembly,
## following the Bootstrap distribution pattern.  The pinned mktext release asset
## is cached under a version-addressed local filename, verified before every build,
## embedded unchanged, and deliberately excluded from adrctl comment filtering.
build: $(SOURCE_FILES) verify-mktext
	mkdir -p "$(DIST_DIR)"
	{ \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Canonical product: adrctl'; \
		printf '%s\n' '# Embedded dependency: mktext v$(MKTEXT_VERSION)'; \
		printf '\n'; \
		printf '__adrctl_version=%q\n' "$(VERSION)"; \
		printf '__adrctl_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__adrctl_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
		sed '/^#/d' $(LIB_FILES); \
		printf '\n'; \
		cat "$(MKTEXT_ARTIFACT)"; \
		printf '\n'; \
		sed '/^#/d' "$(ENTRYPOINT)"; \
	} >"$(DIST_SCRIPT).tmp"
	chmod 0755 "$(DIST_SCRIPT).tmp"
	mv "$(DIST_SCRIPT).tmp" "$(DIST_SCRIPT)"
	bash -n "$(DIST_SCRIPT)"

## Acquire the pinned mktext release artifact and verify its published digest.
##
## The local cache filename includes the pinned version so changing the pin cannot
## silently reuse bytes downloaded for an earlier release.
$(MKTEXT_ARTIFACT):
	mkdir -p "$(VENDOR_DIR)"
	curl -fsSL "$(MKTEXT_URL)" -o "$@.tmp"
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(MKTEXT_SHA256)" "$@.tmp" | sha256sum -c - >/dev/null; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$@.tmp" | awk '{print $$1}')"; \
		[[ "$${actual}" == "$(MKTEXT_SHA256)" ]]; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available' >&2; \
		exit 1; \
	fi
	chmod 0644 "$@.tmp"
	mv "$@.tmp" "$@"

verify-mktext: $(MKTEXT_ARTIFACT)
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(MKTEXT_SHA256)" "$(MKTEXT_ARTIFACT)" | sha256sum -c -; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(MKTEXT_ARTIFACT)" | awk '{print $$1}')"; \
		[[ "$${actual}" == "$(MKTEXT_SHA256)" ]]; \
		printf '%s: OK\n' "$(MKTEXT_ARTIFACT)"; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available' >&2; \
		exit 1; \
	fi

## Validate maintained Bash source.
##
## The modules are concatenated in the explicit build order above.  ShellCheck
## analyzes source files independently, so modules that intentionally consume
## private globals from earlier modules need SC2154 excluded for that file.  The
## command layer also passes caller-owned arrays by variable name to nameref
## helpers, which ShellCheck cannot follow statically; SC2034/SC2190 are excluded
## only for that module.  All other ShellCheck diagnostics remain enabled.
check:
	bash -n $(SOURCE_FILES)
	shellcheck lib/runtime.bash lib/config.bash lib/project.bash $(ENTRYPOINT)
	shellcheck -e SC2154 lib/render.bash lib/adr.bash
	shellcheck -e SC2034,SC2154,SC2190 lib/commands.bash

## Format maintained Bash source using the project formatter contract.
format:
	shfmt -w -i 2 -ci $(SOURCE_FILES)

## Build and run observable behavior tests against the generated artifact.
test: build
	bats $(TEST_SCRIPTS)

## Produce JUnit-compatible test output for CI artifacts.
test-report: build
	mkdir -p "$(TEST_RESULTS_DIR)"
	bats --formatter junit $(TEST_SCRIPTS) >"$(TEST_RESULTS_DIR)/bats.xml"

## Download the Bash Doxygen filter used for reference documentation.
$(DOXYGEN_BASH_FILTER):
	mkdir -p "$(VENDOR_DIR)"
	curl -fsSL "$(DOXYGEN_BASH_FILTER_URL)" -o "$@.tmp"
	chmod 0755 "$@.tmp"
	mv "$@.tmp" "$@"

## Remove generated reference documentation while preserving its sentinel README.
docs-clean:
	@if [[ -d "$(REFERENCE_DOC_DIR)" ]]; then \
		find "$(REFERENCE_DOC_DIR)" -mindepth 1 ! -name README.md -exec rm -rf {} +; \
	fi

## Regenerate browsable Doxygen reference documentation.
docs: docs-clean $(DOXYGEN_BASH_FILTER)
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile
	{ \
		printf '%s\n' '# Reference Documentation'; \
		printf '\n'; \
		printf '%s\n' 'This directory contains documentation generated from adrctl Bash source.'; \
		printf '%s\n' 'Do not edit generated reference files manually.'; \
		printf '\n'; \
		printf '%s\n' 'Regenerate with `make docs`.'; \
	} >"$(REFERENCE_DOC_DIR)/README.md"

docs-stage: docs
	git add -A "$(REFERENCE_DOC_DIR)"

## Generate SHA-256 for the exact consumer artifact.
checksums: build
	cd "$(DIST_DIR)" && sha256sum "$(notdir $(DIST_SCRIPT))" >"$(notdir $(DIST_CHECKSUM))"

clean:
	rm -rf "$(DIST_DIR)" "$(TEST_RESULTS_DIR)"

distclean: clean docs-clean
	rm -f "$(VENDOR_DIR)"/mktext-v*.bash "$(VENDOR_DIR)/mktext.bash" "$(DOXYGEN_BASH_FILTER)"
	-rmdir "$(VENDOR_DIR)" >/dev/null 2>&1
