# Canonical development, validation, documentation, and release entry points.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

DIST_DIR := dist
DIST_DEV_SCRIPT := $(DIST_DIR)/adrctl.dev.bash
DIST_SCRIPT := $(DIST_DIR)/adrctl.bash
DIST_MIN_SCRIPT := $(DIST_DIR)/adrctl.min.bash
DIST_SCRIPTS := $(DIST_DEV_SCRIPT) $(DIST_SCRIPT) $(DIST_MIN_SCRIPT)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))
LEGACY_CHECKSUMS := $(addsuffix .256,$(DIST_SCRIPTS))

LIB_FILES := \
	lib/runtime.bash \
	lib/config.bash \
	lib/project.bash \
	lib/render.bash \
	lib/adr.bash \
	lib/commands.bash \
	lib/graph.bash
ENTRYPOINT := src/adrctl.bash
SOURCE_FILES := $(LIB_FILES) $(ENTRYPOINT)
CHECK_BASH_FILES := $(shell find lib src tests -type f -name '*.bash' -print | LC_ALL=C sort)

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
MKTEXT_ARTIFACT := $(VENDOR_DIR)/mktext.bash
BASH_MINIFIER := $(VENDOR_DIR)/bash-minifier.bash

TESTS_DIR := tests
TEST_SCRIPTS := $(TESTS_DIR)/*.bats
TEST_RESULTS_DIR := test-results

DOXYGEN_BASH_FILTER := $(VENDOR_DIR)/doxygen-bash.awk
REFERENCE_DOC_DIR := doc/reference

VERSION ?= 0.0.0-dev
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all build check checksums clean deps deps-check distclean docs docs-clean FORCE format test test-report verify-bashdeps

## Synchronize dependencies, then build every distribution flavor.
##
## The recursive Make invocation keeps the ordering explicit even when Make runs
## with parallel jobs.  Plain `make build` remains network-free and does not
## synchronize or verify dependencies.
all: deps
	$(MAKE) --no-print-directory build

## Build the development, standard, and minified distribution artifacts.
##
## `adrctl.dev.bash` retains comments from every assembled source/library input.
## `adrctl.bash` removes full-line comments from those inputs while retaining the
## generated artifact-identification header.  `adrctl.min.bash` is produced by
## applying the manifest-managed Bash-Minifier to the completed standard artifact.
## This target does not acquire or verify external dependencies.
build: $(SOURCE_FILES)
	@test -r "$(MKTEXT_ARTIFACT)" || { \
		printf '%s\n' 'Missing build dependency vendor/mktext.bash; run make deps or make all' >&2; \
		exit 1; \
	}
	@test -r "$(BASH_MINIFIER)" || { \
		printf '%s\n' 'Missing build dependency vendor/bash-minifier.bash; run make deps or make all' >&2; \
		exit 1; \
	}
	mkdir -p "$(DIST_DIR)"
	@write_header() { \
		flavor=$$1; \
		printf '%s\n' '#!/usr/bin/env bash'; \
		printf '%s\n' '#'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Canonical product: adrctl'; \
		printf '# Distribution flavor: %s\n' "$$flavor"; \
		printf '%s\n' '# Embedded dependency: mktext from dependencies.txt'; \
		printf '\n'; \
		printf '__adrctl_version=%q\n' "$(VERSION)"; \
		printf '__adrctl_build_date=%q\n' "$(BUILD_DATE)"; \
		printf '__adrctl_build_commit=%q\n' "$(BUILD_COMMIT)"; \
		printf '\n'; \
	}; \
	strip_full_line_comments() { \
		sed '/^[[:space:]]*#/d' "$$@"; \
	}; \
	{ \
		write_header development; \
		cat $(LIB_FILES); \
		printf '\n'; \
		cat "$(MKTEXT_ARTIFACT)"; \
		printf '\n'; \
		cat "$(ENTRYPOINT)"; \
	} >"$(DIST_DEV_SCRIPT).tmp"; \
	{ \
		write_header standard; \
		strip_full_line_comments $(LIB_FILES); \
		printf '\n'; \
		strip_full_line_comments "$(MKTEXT_ARTIFACT)"; \
		printf '\n'; \
		strip_full_line_comments "$(ENTRYPOINT)"; \
	} >"$(DIST_SCRIPT).tmp"; \
	chmod 0755 "$(DIST_DEV_SCRIPT).tmp" "$(DIST_SCRIPT).tmp"; \
	bash "$(BASH_MINIFIER)" -F <"$(DIST_SCRIPT).tmp" >"$(DIST_MIN_SCRIPT).tmp"; \
	chmod 0755 "$(DIST_MIN_SCRIPT).tmp"; \
	for artifact in "$(DIST_DEV_SCRIPT).tmp" "$(DIST_SCRIPT).tmp" "$(DIST_MIN_SCRIPT).tmp"; do \
		bash -n "$$artifact"; \
	done; \
	write_checksum() { \
		artifact=$$1; \
		checksum=$$2; \
		final_name=$$3; \
		if command -v sha256sum >/dev/null 2>&1; then \
			digest="$$(sha256sum "$$artifact" | awk '{print $$1}')"; \
		elif command -v shasum >/dev/null 2>&1; then \
			digest="$$(shasum -a 256 "$$artifact" | awk '{print $$1}')"; \
		else \
			printf '%s\n' 'No SHA-256 implementation is available for build artifacts' >&2; \
			exit 1; \
		fi; \
		printf '%s  %s\n' "$$digest" "$$final_name" >"$$checksum"; \
	}; \
	write_checksum "$(DIST_DEV_SCRIPT).tmp" "$(DIST_DEV_SCRIPT).sha256.tmp" "$(notdir $(DIST_DEV_SCRIPT))"; \
	write_checksum "$(DIST_SCRIPT).tmp" "$(DIST_SCRIPT).sha256.tmp" "$(notdir $(DIST_SCRIPT))"; \
	write_checksum "$(DIST_MIN_SCRIPT).tmp" "$(DIST_MIN_SCRIPT).sha256.tmp" "$(notdir $(DIST_MIN_SCRIPT))"; \
	rm -f $(LEGACY_CHECKSUMS); \
	mv "$(DIST_DEV_SCRIPT).tmp" "$(DIST_DEV_SCRIPT)"; \
	mv "$(DIST_SCRIPT).tmp" "$(DIST_SCRIPT)"; \
	mv "$(DIST_MIN_SCRIPT).tmp" "$(DIST_MIN_SCRIPT)"; \
	mv "$(DIST_DEV_SCRIPT).sha256.tmp" "$(DIST_DEV_SCRIPT).sha256"; \
	mv "$(DIST_SCRIPT).sha256.tmp" "$(DIST_SCRIPT).sha256"; \
	mv "$(DIST_MIN_SCRIPT).sha256.tmp" "$(DIST_MIN_SCRIPT).sha256"

## Force the bootstrap file target to validate cached bytes whenever requested.
FORCE:

## Bootstrap the pinned released bashdeps executable used to process dependencies.txt.
##
## Make directly owns only this bootstrap dependency.  Correct cached bytes avoid
## network access.  Missing or mismatched bytes are replaced only after a staged
## download matches the committed SHA-256 digest.
$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			actual="$$(shasum -a 256 "$$path" | awk '{print $$1}')"; \
			[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
		else \
			return 2; \
		fi; \
	}; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then \
		chmod 0755 "$@"; \
		exit 0; \
	fi; \
	if ! command -v curl >/dev/null 2>&1; then \
		printf '%s\n' 'curl is required to bootstrap bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	tmp="$@.tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	if ! verify_hash "$$tmp"; then \
		printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; \
		exit 1; \
	fi; \
	chmod 0755 "$$tmp"; \
	mv "$$tmp" "$@"; \
	trap - EXIT

## Verify the already-present bashdeps bootstrap without network access or repair.
verify-bashdeps:
	@test -x "$(BASHDEPS)" || { \
		printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; \
		exit 1; \
	}
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')"; \
		[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi

## Synchronize manifest-managed project dependencies through bashdeps.
deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

## Verify bootstrap and manifest-managed dependency state without network access.
deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

## Validate every maintained .bash file discovered under lib/, src/, and tests/.
##
## Artifact assembly keeps an explicit module order, while validation discovers
## Bash sources recursively so newly added files cannot silently escape checks.
check:
	bash -n $(CHECK_BASH_FILES)
	shellcheck $(CHECK_BASH_FILES)

## Format maintained Bash source using the project formatter contract.
format:
	shfmt -w -i 2 -ci $(SOURCE_FILES)

## Build and run the observable behavior suite against every release executable.
test: build
	@for artifact in $(DIST_SCRIPTS); do \
		printf 'Testing %s\n' "$$artifact"; \
		ADRCTL_ARTIFACT="$(CURDIR)/$$artifact" bats $(TEST_SCRIPTS) || exit $$?; \
	done

## Produce one JUnit-compatible test report for each release executable flavor.
test-report: build
	mkdir -p "$(TEST_RESULTS_DIR)"
	@for artifact in $(DIST_SCRIPTS); do \
		name="$${artifact##*/}"; \
		ADRCTL_ARTIFACT="$(CURDIR)/$$artifact" \
			bats --formatter junit $(TEST_SCRIPTS) >"$(TEST_RESULTS_DIR)/bats-$${name}.xml" || exit $$?; \
	done

## Remove generated Doxygen reference documentation.
docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"

## Regenerate browsable Doxygen reference documentation.
##
## The filter is a manifest-managed data artifact, so this consumer target owns
## the executable mode needed by Doxygen rather than asking bashdeps to infer it.
docs: docs-clean deps
	chmod 0755 "$(DOXYGEN_BASH_FILTER)"
	mkdir -p "$(REFERENCE_DOC_DIR)"
	doxygen Doxyfile

## Ensure the six build artifacts exist; checksums are generated by make build.
checksums: build
	@for artifact in $(DIST_SCRIPTS) $(DIST_CHECKSUMS); do \
		test -f "$$artifact"; \
	done

clean:
	rm -rf "$(DIST_DIR)" "$(TEST_RESULTS_DIR)" "$(VENDOR_DIR)"

distclean: clean docs-clean
