#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/.." && pwd -P)"
  ADRCTL="${REPO_ROOT}/dist/adrctl.bash"
}

@test "generated artifact strips Doxygen comments from maintained adrctl source" {
  [ -x "${ADRCTL}" ]

  run grep -E '^##[[:space:]]+@' "${ADRCTL}"
  [ "${status}" -eq 1 ]
}

@test "generated artifact retains its build header" {
  run grep -F '# Generated by make build. Do not edit directly.' "${ADRCTL}"

  [ "${status}" -eq 0 ]
}
