#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "${BATS_TEST_DIRNAME}/.." && pwd -P)"
  ADRCTL="${ADRCTL_ARTIFACT:-${REPO_ROOT}/dist/adrctl.bash}"
  ARTIFACT_NAME="${ADRCTL##*/}"
}

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

@test "distribution artifact has the expected maintained-comment profile" {
  [ -x "${ADRCTL}" ]

  run grep -E '^##[[:space:]]+@' "${ADRCTL}"
  case "${ARTIFACT_NAME}" in
    adrctl.dev.bash)
      [ "${status}" -eq 0 ]
      ;;
    adrctl.bash | adrctl.min.bash)
      [ "${status}" -eq 1 ]
      ;;
    *)
      false
      ;;
  esac
}

@test "generated build header is retained before minification" {
  run grep -F '# Generated by make build. Do not edit directly.' "${ADRCTL}"

  case "${ARTIFACT_NAME}" in
    adrctl.dev.bash | adrctl.bash)
      [ "${status}" -eq 0 ]
      ;;
    adrctl.min.bash)
      [ "${status}" -eq 1 ]
      ;;
    *)
      false
      ;;
  esac
}

@test "build emits three executable artifacts and three valid .256 files" {
  local artifact checksum expected recorded_name

  for artifact in \
    "${REPO_ROOT}/dist/adrctl.dev.bash" \
    "${REPO_ROOT}/dist/adrctl.bash" \
    "${REPO_ROOT}/dist/adrctl.min.bash"; do
    [ -x "${artifact}" ]
    checksum="${artifact}.256"
    [ -f "${checksum}" ]
    read -r expected recorded_name <"${checksum}"
    [ "${expected}" = "$(sha256_of "${artifact}")" ]
    [ "${recorded_name}" = "${artifact##*/}" ]
  done

  [ ! -e "${REPO_ROOT}/dist/adrctl.bash.sha256" ]
}

@test "minified artifact is the deterministic Bash-Minifier transform of the standard artifact" {
  local expected

  expected="${BATS_TEST_TMPDIR}/expected-minified.bash"
  bash "${REPO_ROOT}/vendor/bash-minifier.bash" \
    -F \
    <"${REPO_ROOT}/dist/adrctl.bash" \
    >"${expected}"

  cmp "${expected}" "${REPO_ROOT}/dist/adrctl.min.bash"
  [ "$(wc -c <"${REPO_ROOT}/dist/adrctl.min.bash")" -lt \
    "$(wc -c <"${REPO_ROOT}/dist/adrctl.bash")" ]
}

@test "deps converges stale mktext bytes to the manifest digest" {
  local fixture_root fixture vendor_dir fake_bin manifest bootstrap_digest digest curl_sentinel

  fixture_root="${BATS_TEST_TMPDIR}/dependency-convergence"
  fixture="${fixture_root}/expected-mktext.bash"
  vendor_dir="${fixture_root}/vendor"
  fake_bin="${fixture_root}/bin"
  manifest="${fixture_root}/dependencies.txt"
  curl_sentinel="${fixture_root}/curl-called"
  mkdir -p "${vendor_dir}" "${fake_bin}"

  cp "${REPO_ROOT}/Makefile" "${fixture_root}/Makefile"
  cp "${REPO_ROOT}/vendor/bashdeps.bash" "${vendor_dir}/bashdeps.bash"
  chmod 0755 "${vendor_dir}/bashdeps.bash"
  bootstrap_digest="$(sha256_of "${vendor_dir}/bashdeps.bash")"

  cat >"${fixture}" <<'EOF'
#!/usr/bin/env bash
readonly __mktext_fixture=1
EOF
  digest="$(sha256_of "${fixture}")"

  printf '%s\n' 'stale dependency bytes' >"${vendor_dir}/mktext.bash"
  printf '%s\n' \
    "id=fixture-mktext@2 url=https://example.test/mktext.bash dest=vendor/mktext.bash digest=sha256:${digest}" \
    >"${manifest}"

  cat >"${fake_bin}/curl" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

output=''
while (($#)); do
  case $1 in
    --output)
      output=$2
      shift 2
      ;;
    --)
      shift
      [[ $# -eq 1 ]]
      shift
      ;;
    *)
      shift
      ;;
  esac
done

[[ -n $output ]]
if [[ -n ${BASHDEPS_CURL_SENTINEL:-} ]]; then
  : >"${BASHDEPS_CURL_SENTINEL}"
fi
cp "${BASHDEPS_TEST_FIXTURE}" "$output"
EOF
  chmod 0755 "${fake_bin}/curl"

  run env \
    PATH="${fake_bin}:${PATH}" \
    BASHDEPS_TEST_FIXTURE="${fixture}" \
    make -C "${fixture_root}" deps \
      CHECK_BASH_FILES= \
      BASHDEPS_SHA256="${bootstrap_digest}" \
      BASHDEPS_URL=https://example.test/bashdeps.bash

  [ "${status}" -eq 0 ]
  cmp "${fixture}" "${vendor_dir}/mktext.bash"

  printf '%s\n' 'tampered after synchronization' >"${vendor_dir}/mktext.bash"
  run env \
    PATH="${fake_bin}:${PATH}" \
    BASHDEPS_TEST_FIXTURE="${fixture}" \
    BASHDEPS_CURL_SENTINEL="${curl_sentinel}" \
    make -C "${fixture_root}" deps-check \
      CHECK_BASH_FILES= \
      BASHDEPS_SHA256="${bootstrap_digest}"

  [ "${status}" -ne 0 ]
  [ ! -e "${curl_sentinel}" ]
}

@test "build consumes prepared dependencies without dependency synchronization" {
  local fixture_root cache_dir dist_dir

  fixture_root="${BATS_TEST_TMPDIR}/prepared-build"
  cache_dir="${fixture_root}/vendor"
  dist_dir="${fixture_root}/dist"
  mkdir -p "${cache_dir}" "${dist_dir}"
  : >"${dist_dir}/adrctl.bash.sha256"

  cat >"${cache_dir}/mktext.bash" <<'EOF'
#!/usr/bin/env bash
## @brief Fixture comment from an embedded library.
readonly __mktext_fixture_prepared=1
EOF
  cp "${REPO_ROOT}/vendor/bash-minifier.bash" "${cache_dir}/bash-minifier.bash"

  run make -C "${REPO_ROOT}" build \
    VENDOR_DIR="${cache_dir}" \
    DIST_DIR="${dist_dir}"

  [ "${status}" -eq 0 ]
  [ -x "${dist_dir}/adrctl.dev.bash" ]
  [ -x "${dist_dir}/adrctl.bash" ]
  [ -x "${dist_dir}/adrctl.min.bash" ]
  grep -F 'readonly __mktext_fixture_prepared=1' "${dist_dir}/adrctl.dev.bash"
  grep -F 'readonly __mktext_fixture_prepared=1' "${dist_dir}/adrctl.bash"
  grep -F 'readonly __mktext_fixture_prepared=1' "${dist_dir}/adrctl.min.bash"
  grep -F '## @brief Fixture comment from an embedded library.' \
    "${dist_dir}/adrctl.dev.bash"
  ! grep -F '## @brief Fixture comment from an embedded library.' \
    "${dist_dir}/adrctl.bash"
  ! grep -F '## @brief Fixture comment from an embedded library.' \
    "${dist_dir}/adrctl.min.bash"
  [ ! -e "${dist_dir}/adrctl.bash.sha256" ]
  [ ! -e "${cache_dir}/bashdeps.bash" ]
}

@test "clean removes generated distribution test results and vendor state" {
  local fixture_root cache_dir dist_dir results_dir

  fixture_root="${BATS_TEST_TMPDIR}/clean"
  cache_dir="${fixture_root}/vendor"
  dist_dir="${fixture_root}/dist"
  results_dir="${fixture_root}/test-results"
  mkdir -p "${cache_dir}" "${dist_dir}" "${results_dir}"
  : >"${cache_dir}/dependency"
  : >"${dist_dir}/artifact"
  : >"${results_dir}/results"

  run make -C "${REPO_ROOT}" clean \
    VENDOR_DIR="${cache_dir}" \
    DIST_DIR="${dist_dir}" \
    TEST_RESULTS_DIR="${results_dir}"

  [ "${status}" -eq 0 ]
  [ ! -e "${cache_dir}" ]
  [ ! -e "${dist_dir}" ]
  [ ! -e "${results_dir}" ]
}
